language: php

php:
  - 5.6
  - 7

before_script:
  - pear install PHP_CodeSniffer
  - phpenv rehash
  - composer self-update

script:
  - composer install --dev
  - composer validate
  - phpcs --standard=psr2 src/

branches:
  only:
    - master
