language: php

php:
  - 5.3
  - 5.4

before_script:
  - pear install PHP_CodeSniffer
  - phpenv rehash
  - composer self-update

script:
  - composer install --dev
  - composer validate
  - phpcs --standard=psr2 src/

